
import "./globals.scss";
import Footer from "@/components/footer/Footer";
import ReduxProvider from "@/redux/ReduxProvider";
import { Toaster } from "react-hot-toast";


export const metadata = {
  title: "EduVerse",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ReduxProvider>
      <html lang="en">
        <body>
          <Toaster position="bottom-center" />
          {children}
          <Footer />
        </body>
      </html>
    </ReduxProvider>
  );
}
