
import "./globals.scss";
import Footer from "@/components/footer/Footer";


export const metadata = {
  title: "EduVerse",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
        <Footer />
      </body>
    </html>
  );
}
